---
name: "Pull Request Add Milestone"
on:
  pull_request:
    types:
      - opened
jobs:
  milestone:
    runs-on: ubuntu-latest
    steps:
      - uses: iyu/actions-milestone@v1
        with:
          configuration-path: .github/milestone.yml
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
